//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Test_DB.bd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public string Name { get; set; }
        public int Id { get; set; }
        public Nullable<double> Price { get; set; }
        public Nullable<int> QTy { get; set; }
        public string Description { get; set; }
    }
}
